# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Industrieel Ingenieur EM\6-Bachelorproef Elektromechanica\Programma's\Python\GUI_Robot_Zuurkast_Python\GUI_robot_controls.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(2188, 859)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.moveX = QtWidgets.QPushButton(self.centralwidget)
        self.moveX.setGeometry(QtCore.QRect(400, 570, 101, 31))
        self.moveX.setObjectName("moveX")
        self.moveZ = QtWidgets.QPushButton(self.centralwidget)
        self.moveZ.setGeometry(QtCore.QRect(620, 570, 101, 31))
        self.moveZ.setObjectName("moveZ")
        self.moveY = QtWidgets.QPushButton(self.centralwidget)
        self.moveY.setEnabled(False)
        self.moveY.setGeometry(QtCore.QRect(510, 570, 101, 31))
        self.moveY.setObjectName("moveY")
        self.stopping = QtWidgets.QPushButton(self.centralwidget)
        self.stopping.setGeometry(QtCore.QRect(180, 572, 101, 31))
        self.stopping.setObjectName("stopping")
        self.Homing = QtWidgets.QPushButton(self.centralwidget)
        self.Homing.setGeometry(QtCore.QRect(69, 572, 101, 31))
        self.Homing.setObjectName("Homing")
        self.joystick_control = QtWidgets.QCheckBox(self.centralwidget)
        self.joystick_control.setGeometry(QtCore.QRect(140, 620, 71, 21))
        self.joystick_control.setObjectName("joystick_control")
        self.move_command = QtWidgets.QLineEdit(self.centralwidget)
        self.move_command.setGeometry(QtCore.QRect(510, 620, 101, 31))
        self.move_command.setObjectName("move_command")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(620, 630, 31, 16))
        self.label.setObjectName("label")
        self.posX = QtWidgets.QTextBrowser(self.centralwidget)
        self.posX.setEnabled(False)
        self.posX.setGeometry(QtCore.QRect(1210, 570, 101, 31))
        self.posX.setObjectName("posX")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(970, 570, 221, 31))
        self.textEdit.setObjectName("textEdit")
        self.posY = QtWidgets.QTextBrowser(self.centralwidget)
        self.posY.setEnabled(False)
        self.posY.setGeometry(QtCore.QRect(1320, 570, 101, 31))
        self.posY.setObjectName("posY")
        self.posZ = QtWidgets.QTextBrowser(self.centralwidget)
        self.posZ.setEnabled(False)
        self.posZ.setGeometry(QtCore.QRect(1430, 570, 101, 31))
        self.posZ.setObjectName("posZ")
        self.widget_visu = Graph(self.centralwidget)
        self.widget_visu.setGeometry(QtCore.QRect(0, 30, 2000, 500))
        self.widget_visu.setObjectName("widget_visu")
        self.CurrentPositionBasket = QtWidgets.QSpinBox(self.centralwidget)
        self.CurrentPositionBasket.setGeometry(QtCore.QRect(451, 700, 51, 31))
        self.CurrentPositionBasket.setMaximum(12)
        self.CurrentPositionBasket.setObjectName("CurrentPositionBasket")
        self.clear_all = QtWidgets.QPushButton(self.centralwidget)
        self.clear_all.setGeometry(QtCore.QRect(820, 700, 91, 31))
        self.clear_all.setObjectName("clear_all")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(260, 700, 181, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(510, 700, 141, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.NewPositionBasket = QtWidgets.QSpinBox(self.centralwidget)
        self.NewPositionBasket.setGeometry(QtCore.QRect(660, 700, 51, 31))
        self.NewPositionBasket.setMaximum(12)
        self.NewPositionBasket.setObjectName("NewPositionBasket")
        self.ApplyMovement = QtWidgets.QPushButton(self.centralwidget)
        self.ApplyMovement.setGeometry(QtCore.QRect(720, 700, 93, 31))
        self.ApplyMovement.setObjectName("ApplyMovement")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(260, 750, 181, 51))
        self.textEdit_4.setObjectName("textEdit_4")
        self.sequence_toggle = QtWidgets.QCheckBox(self.centralwidget)
        self.sequence_toggle.setGeometry(QtCore.QRect(1180, 640, 151, 21))
        self.sequence_toggle.setCheckable(True)
        self.sequence_toggle.setChecked(False)
        self.sequence_toggle.setObjectName("sequence_toggle")
        self.sim = QtWidgets.QRadioButton(self.centralwidget)
        self.sim.setGeometry(QtCore.QRect(1700, 670, 141, 31))
        self.sim.setAutoExclusive(False)
        self.sim.setObjectName("sim")
        self.AddNewBasket = QtWidgets.QPushButton(self.centralwidget)
        self.AddNewBasket.setGeometry(QtCore.QRect(10, 750, 231, 31))
        self.AddNewBasket.setObjectName("AddNewBasket")
        self.OpenLid = QtWidgets.QPushButton(self.centralwidget)
        self.OpenLid.setGeometry(QtCore.QRect(720, 760, 93, 31))
        self.OpenLid.setObjectName("OpenLid")
        self.CloseLid = QtWidgets.QPushButton(self.centralwidget)
        self.CloseLid.setGeometry(QtCore.QRect(820, 760, 93, 31))
        self.CloseLid.setObjectName("CloseLid")
        self.LiqBoxNr = QtWidgets.QSpinBox(self.centralwidget)
        self.LiqBoxNr.setGeometry(QtCore.QRect(660, 760, 51, 31))
        self.LiqBoxNr.setMinimum(1)
        self.LiqBoxNr.setMaximum(12)
        self.LiqBoxNr.setObjectName("LiqBoxNr")
        self.relative_absolute = QtWidgets.QScrollBar(self.centralwidget)
        self.relative_absolute.setGeometry(QtCore.QRect(730, 570, 161, 31))
        self.relative_absolute.setMaximum(1)
        self.relative_absolute.setPageStep(1)
        self.relative_absolute.setProperty("value", 0)
        self.relative_absolute.setSliderPosition(0)
        self.relative_absolute.setOrientation(QtCore.Qt.Horizontal)
        self.relative_absolute.setInvertedAppearance(False)
        self.relative_absolute.setObjectName("relative_absolute")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(750, 550, 131, 16))
        self.label_2.setObjectName("label_2")
        self.gripper = QtWidgets.QPushButton(self.centralwidget)
        self.gripper.setGeometry(QtCore.QRect(400, 620, 101, 31))
        self.gripper.setObjectName("gripper")
        self.LidIsOpen = QtWidgets.QCheckBox(self.centralwidget)
        self.LidIsOpen.setGeometry(QtCore.QRect(970, 770, 91, 20))
        self.LidIsOpen.setObjectName("LidIsOpen")
        self.FinishNewSequence = QtWidgets.QPushButton(self.centralwidget)
        self.FinishNewSequence.setEnabled(False)
        self.FinishNewSequence.setGeometry(QtCore.QRect(1390, 670, 131, 31))
        self.FinishNewSequence.setObjectName("FinishNewSequence")
        self.SequenceSelection = QtWidgets.QComboBox(self.centralwidget)
        self.SequenceSelection.setGeometry(QtCore.QRect(1610, 640, 71, 31))
        self.SequenceSelection.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.SequenceSelection.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.SequenceSelection.setObjectName("SequenceSelection")
        self.SequenceNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.SequenceNumber.setEnabled(False)
        self.SequenceNumber.setGeometry(QtCore.QRect(1310, 670, 71, 31))
        self.SequenceNumber.setSmallDecimalPoint(False)
        self.SequenceNumber.setObjectName("SequenceNumber")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(1200, 670, 111, 31))
        self.label_3.setObjectName("label_3")
        self.delete_seq = QtWidgets.QRadioButton(self.centralwidget)
        self.delete_seq.setGeometry(QtCore.QRect(1700, 700, 131, 31))
        self.delete_seq.setCheckable(True)
        self.delete_seq.setChecked(False)
        self.delete_seq.setAutoExclusive(False)
        self.delete_seq.setObjectName("delete_seq")
        self.DeleteLastCommand = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteLastCommand.setEnabled(False)
        self.DeleteLastCommand.setGeometry(QtCore.QRect(1390, 710, 131, 31))
        self.DeleteLastCommand.setObjectName("DeleteLastCommand")
        self.EditSeq = QtWidgets.QCheckBox(self.centralwidget)
        self.EditSeq.setGeometry(QtCore.QRect(1700, 640, 111, 31))
        self.EditSeq.setObjectName("EditSeq")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2188, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.SequenceSelection.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.moveX.setText(_translate("MainWindow", "MoveX"))
        self.moveZ.setText(_translate("MainWindow", "MoveZ"))
        self.moveY.setText(_translate("MainWindow", "MoveY"))
        self.stopping.setText(_translate("MainWindow", "Stop"))
        self.Homing.setText(_translate("MainWindow", "Home"))
        self.joystick_control.setText(_translate("MainWindow", "Joystick"))
        self.label.setText(_translate("MainWindow", "mm"))
        self.posX.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Current motor positions X / Y / Z :</p></body></html>"))
        self.posY.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.posZ.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.clear_all.setText(_translate("MainWindow", "Clear Baskets"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pick up the basket at position</p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">and place it at position</p></body></html>"))
        self.ApplyMovement.setText(_translate("MainWindow", "Apply"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Position 0      = base station</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Position 1-12 = liquid box</p></body></html>"))
        self.sequence_toggle.setText(_translate("MainWindow", "make new sequence"))
        self.sim.setText(_translate("MainWindow", "Simulate sequence"))
        self.AddNewBasket.setText(_translate("MainWindow", "Add New Basket on the base station"))
        self.OpenLid.setText(_translate("MainWindow", "Open Lid"))
        self.CloseLid.setText(_translate("MainWindow", "Close Lid"))
        self.label_2.setText(_translate("MainWindow", "Relative   |  Absolute"))
        self.gripper.setText(_translate("MainWindow", "Gripper"))
        self.LidIsOpen.setText(_translate("MainWindow", "Lid is open"))
        self.FinishNewSequence.setText(_translate("MainWindow", "Finish sequence"))
        self.label_3.setText(_translate("MainWindow", "Sequence number:"))
        self.delete_seq.setText(_translate("MainWindow", "Delete sequence"))
        self.DeleteLastCommand.setText(_translate("MainWindow", "Delete last command"))
        self.EditSeq.setText(_translate("MainWindow", "Edit sequence"))
from zuurkast_setup import Graph


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
